[package]
name = "portable-document-comparator"
version = "0.1.0"
authors = ["Zoltan Kovari"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/zkoevaari/portable-document-comparator.git"

[dependencies]
